version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0"
    volumes:
      - .:/Y_LAB
    ports:
      - 8080:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]



  redis_cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data



volumes:
  postgres_data:
  cache:
