version: '3'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/Y_LAB
    ports:
      - 8080:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres

    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
