version: '3.8'

services:
  web:
    build: .
    entrypoint: sh -c "alembic upgrade head && pytest"
    volumes:
      - .:/Y_LAB
    ports:
      - 8080:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]